apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - port: 5432

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:11.2-alpine
        env:
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
        envFrom:
          - secretRef:
              name: db-secrets
          - configMapRef:
              name: db-config
        ports:
          - containerPort: 5432
        volumeMounts:
          - name: postgres-data
            mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      storageClassName: vks-storage-policy
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  type: LoadBalancer
  loadBalancerIP: "10.96.220.181"
  selector:
    app: api
  ports:
    - port: 5001
      targetPort: 5000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      initContainers:
      - name: wait-for-postgres
        image: busybox:1.28
        command: ['sh', '-c', "until nc -zv postgres 5432; do echo waiting; sleep 2; done"]
      containers:
      - name: api
        image: vsgdev/movie-voting-api:2026v1
        envFrom:
          - secretRef:
              name: db-secrets
          - configMapRef:
              name: db-config
        ports:
          - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: client
spec:
  type: LoadBalancer
  loadBalancerIP: "10.100.55.133"
  selector:
    app: client
  ports:
    - port: 80
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: vsgdev/movie-voting-client:2026v1
        env:
          - name: REACT_APP_API_URL
            value: "http://10.96.220.181:5001"
        ports:
          - containerPort: 3000